In [1]:
from manim import *
# magic cell syntax : %%manim -qh -v WARNING {scene name}

Manim Community v0.15.2

In [2]:
%%manim -qk -v WARNING --disable_caching Towing_scene
    
class Towing_scene(Scene):
    def ttnparr(self, t): #t - tracker
        return np.array([i.get_value() for i in t])
    
    def above_vector(self, mobj, vec_mobj):
        mobj.next_to(vec_mobj, UP)
        
    def update_vector(
        self, 
        mobj_vector, 
        mobj_tracker, 
        center_mobj, 
        color,
        stroke_width=3):
        mobj_vector.become(
            Arrow(
                start=center_mobj.get_center(),
                end=self.ttnparr(mobj_tracker) + center_mobj.get_center(),
                buff=0,
                color=color,
                stroke_width=stroke_width
            )
        )
    
    def add_trackers(self, trackers1, trackers2):
        given_trackers = zip(trackers1, trackers2)
        resultant_trackers = []
        for t1, t2 in given_trackers:
            active_tracker = ValueTracker(t1.get_value()+t2.get_value())
            resultant_trackers.append(active_tracker)
        return resultant_trackers

    def construct(self):
        
        box = Square(side_length=2, color=GREEN, fill_opacity=0.2)
        
        f1_trackers = [ValueTracker(-3), ValueTracker(0), ValueTracker(0)]
        f2_trackers = [ValueTracker(5), ValueTracker(0), ValueTracker(0)]
        
        fsum_trackers = self.add_trackers(f1_trackers, f2_trackers)
        fsum_trackers[0].add_updater(
            lambda m: m.set_value(
                f1_trackers[0].get_value() + f2_trackers[0].get_value()
            )
        )
        fsum_trackers[1].add_updater(
            lambda m: m.set_value(
                f1_trackers[1].get_value() + f2_trackers[1].get_value()
            )
        )
        fsum_trackers[2].add_updater(
            lambda m: m.set_value(
                f1_trackers[2].get_value() + f2_trackers[2].get_value()
            )
        )
        
        vec1 = Arrow(
                start=box.get_center(), 
                end=self.ttnparr(f1_trackers) + box.get_center(), 
                color=BLUE, 
                buff=0
        ).add_updater(
            lambda m: self.update_vector(
                mobj_vector=m, 
                mobj_tracker=f1_trackers, 
                center_mobj=box,
                color=BLUE
            )
        )
        vec1_name = Tex('$\\vec{F_1}$', color=BLUE)\
        .next_to(vec1, UP)
        
        vec2 = Arrow(
                start=box.get_center(), 
                end=self.ttnparr(f2_trackers) + box.get_center(), 
                color=RED, 
                buff=0
        ).add_updater(
            lambda m: self.update_vector(
                mobj_vector=m, 
                mobj_tracker=f2_trackers, 
                center_mobj=box,
                color=RED
            )
        )
        vec2_name = Tex('$\\vec{F_2}$', color=RED).next_to(vec2, UP)

        vec_sum = Arrow(
            start=box.get_center(),
            end=self.ttnparr(fsum_trackers) + box.get_center(),
            color=GREEN,
            buff=0,
            stroke_width=5
        ).add_updater(
            lambda m: self.update_vector(
                mobj_vector=m,
                mobj_tracker=fsum_trackers,
                center_mobj=box,
                color=GREEN,
                stroke_width=5
            )
        )
        vec_sum_name = Tex('$\\vec{F_1}+$'+'$\\vec{F_2}$', color=WHITE)\
        .next_to(vec_sum, UP)
        
        init_vectors = VGroup(vec1.copy(), vec2.copy())
        init_names = VGroup(
            vec1_name.copy().add_updater(lambda m: self.above_vector(m, init_vectors[0])),
            vec2_name.copy().add_updater(lambda m: self.above_vector(m, init_vectors[1]))
        )
        init_items = init_vectors + init_names
        sum_group = VGroup(
            vec_sum, 
            vec_sum_name.add_updater(lambda m: self.above_vector(m, vec_sum))
        )
        self.ttnparr(fsum_trackers)
        self.add(box, init_items)
        self.play(
            FadeOut(init_items),
            ReplacementTransform(
                init_items.copy(), 
                sum_group
            )
        )
        self.play(
            box.animate().shift(2*RIGHT)
        )
        self.play(
            FadeOut(sum_group),
            FadeIn(init_items),
        )
        self.play(
            f1_trackers[0].animate().set_value(-5),
            f2_trackers[0].animate().set_value(3),
            fsum_trackers[0].animate(),
            fsum_trackers[1].animate(),
            fsum_trackers[2].animate()
        )
        self.play(
            FadeOut(init_items),
            ReplacementTransform(init_items.copy(), sum_group)
        )
        self.play(
            box.animate().shift(2*LEFT)
        )
        self.play(
            FadeOut(sum_group),
            FadeIn(init_items),
        )
        self.play(
            f1_trackers[0].animate().set_value(0),
            f1_trackers[1].animate().set_value(-3)
        )
        self.play(
            FadeOut(init_items),
            ReplacementTransform(init_items.copy(), sum_group)
        )
        self.play(
            box.animate().shift(RIGHT+DOWN)
        )
        self.play(
            FadeOut(sum_group),
            FadeIn(init_items),
        )
        self.play(
            f2_trackers[0].animate().set_value(-3),
            f1_trackers[1].animate().set_value(+3)
        )
        self.play(
            FadeOut(init_items),
            ReplacementTransform(init_items.copy(), sum_group)
        )
        self.play(
            box.animate().shift(UP+LEFT)
        )
        self.play(
            FadeOut(sum_group),
            FadeIn(init_items),
        )
        self.play(
            f1_trackers[0].animate().set_value(-3),
            f2_trackers[0].animate().set_value(5),
            f1_trackers[1].animate().set_value(0)
        )

        print(self.ttnparr(f1_trackers))
        print(self.ttnparr(f2_trackers))
        print(self.ttnparr(fsum_trackers))

[-3.  0.  0.]
[5. 0. 0.]
[2. 0. 0.]


In [3]:
%%manim -qh -v WARNING --disable_caching Centripidal_acceleration

def statusis(vec):
    x = vec[0]
    y = vec[1]
    return np.array([-1*y, x, 0])

class Centripidal_acceleration(Scene):
    def construct(self):
        fps = 60
        dt = 1/60
        r = 3
        
        num_plane = NumberPlane()
        
        pth = Circle(color=BLUE, radius=r)
        red_dot = Dot([3, 0, 0], color=RED)
        a_vec = Arrow(
            start=np.array(red_dot.get_center()), 
            end=np.array([0,0,0]),
            buff=0, 
            color=RED
        ).add_updater(
            lambda m: m.become(Arrow(
                start=np.array(red_dot.get_center()), 
                buff=0, 
                end=np.array([0,0,0]), 
                color=RED)
            )
        )
        a_txt = Tex("pagreitis $\\vec{a}$", color=RED).next_to(a_vec)
        a_txt.add_updater(lambda m: m.next_to(a_vec))
        v_vec = Arrow(
            start=np.array(red_dot.get_center()), 
            end=red_dot.get_center() + statusis(red_dot.get_center()),
            buff=0,
            color=GREEN
        ).add_updater(
            lambda m: m.become(
                Arrow(
                    start=np.array(red_dot.get_center()), 
                    end=red_dot.get_center() + statusis(red_dot.get_center()),
                    buff=0,
                    color=GREEN
                )
            )
        )
        v_txt = Tex('greitis $\\vec{v}$', color = GREEN).add_updater(lambda m: m.move_to(v_vec))
        self.add(    
            num_plane,
            pth,
            red_dot,
            a_vec,
            v_vec,
            a_txt,
            v_txt
        )
        self.play(MoveAlongPath(red_dot, pth, run_time=5, rate_func=linear))
        

In [2]:
%%manim -ql -v WARNING --disable_caching Pendulum
import numpy.linalg as linalg

class Pendulum(Scene):
    def pendulum_movement(
        self,
        pendulum_obj,
        dt,
        pin_obj
    ):
        #a = gsin(sintheta)
        unitv_towards_pin = self.unit_vector(
            pin_obj.get_center() - pendulum_obj.get_center()
        )
        force_x = unitv_towards_pin
        force_x[1] = force_x[1] * (-1)
        force_x = self.g * force_x * np.sin(self.angle)
        self.a = force_x / self.m
        pendulum_obj.shift(self.v * dt)
        self.v = self.v + self.a * dt
    
    def angle_from_equilibrium(self):
        self.g = 10
        unit_weight = self.unit_vector(self.weight)
        unit_tension = self.unit_vector(self.tension)
        self.angle = np.arccos(np.dot(unit_weight, unit_tension)) - np.pi
    
    def put_vector_on_mob(self, mob, target_mob, length, arrow):
        pos1 = mob.get_center()
        pos2 = target_mob.get_center()
        displacement = pos2 - pos1
        unit_displacement = self.unit_vector(displacement)
        resultant_vector = unit_displacement * length
        arrow.put_start_and_end_on(pos1, pos1 + resultant_vector)
    
    def unit_vector(self, vector):
        return vector/linalg.norm(vector)
            
    def construct(self):
        self.angle = 0.0
        
        self.g = 9.8
        self.m = 0.1
        # initial_conditions
        self.v = np.array([0., 0., 0.])
        self.a = np.array([0., 0., 0.])
        self.s = np.array([-2., 1])
        self.weight = np.array([0., -2., 0.])
        self.tension = np.array([0., 2., 0.])
        
        pin = Dot(color=RED).shift(4*UP)
        ball = Circle(color=BLUE, fill_opacity=1, radius=1)
        ball.add_updater(
            lambda mob, dt: self.pendulum_movement(
                mob,
                dt,
                pin,
            )
        )
        #Vectors and string (should be fine)
        string = Line(stroke_width=1, start=ball.get_center(), end=pin.get_center()).\
            add_updater(lambda m: m.become(Line(
                stroke_width=1, start=ball.get_center(), end=pin.get_center())
            ))
        tension_vector = Arrow(
            buff=0,
            color=PURPLE
        )
        self.put_vector_on_mob(ball, pin, linalg.norm(self.tension), tension_vector)
        
        tension_vector.add_updater(lambda m: self.put_vector_on_mob(
                ball, pin, linalg.norm(self.tension), m
            )
        )
        weight_vector = Arrow(
            start=ball.get_center(),
            end=ball.get_center()+self.weight,
            color=PURPLE,
            buff=0
        ).add_updater(lambda m: m.put_start_and_end_on(
            ball.get_center(),
            ball.get_center() + self.weight
            )
        )
        self.add(ball, pin, string, tension_vector, weight_vector)
        self.wait(20)
        