In [1]:
from manim import *
# magic cell syntax : %%manim -qh -v WARNING {scene name}

Manim Community v0.15.2

In [2]:
%%manim -qk -v WARNING --disable_caching Towing_scene
    
class Towing_scene(Scene):
    def ttnparr(self, t): #t - tracker
        return np.array([i.get_value() for i in t])
    
    def above_vector(self, mobj, vec_mobj):
        mobj.next_to(vec_mobj, UP)
        
    def update_vector(
        self, 
        mobj_vector, 
        mobj_tracker, 
        center_mobj, 
        color,
        stroke_width=3):
        mobj_vector.become(
            Arrow(
                start=center_mobj.get_center(),
                end=self.ttnparr(mobj_tracker) + center_mobj.get_center(),
                buff=0,
                color=color,
                stroke_width=stroke_width
            )
        )
    
    def add_trackers(self, trackers1, trackers2):
        given_trackers = zip(trackers1, trackers2)
        resultant_trackers = []
        for t1, t2 in given_trackers:
            active_tracker = ValueTracker(t1.get_value()+t2.get_value())
            resultant_trackers.append(active_tracker)
        return resultant_trackers

    def construct(self):
        
        box = Square(side_length=2, color=GREEN, fill_opacity=0.2)
        
        f1_trackers = [ValueTracker(-3), ValueTracker(0), ValueTracker(0)]
        f2_trackers = [ValueTracker(5), ValueTracker(0), ValueTracker(0)]
        
        fsum_trackers = self.add_trackers(f1_trackers, f2_trackers)
        fsum_trackers[0].add_updater(
            lambda m: m.set_value(
                f1_trackers[0].get_value() + f2_trackers[0].get_value()
            )
        )
        fsum_trackers[1].add_updater(
            lambda m: m.set_value(
                f1_trackers[1].get_value() + f2_trackers[1].get_value()
            )
        )
        fsum_trackers[2].add_updater(
            lambda m: m.set_value(
                f1_trackers[2].get_value() + f2_trackers[2].get_value()
            )
        )
        
        vec1 = Arrow(
                start=box.get_center(), 
                end=self.ttnparr(f1_trackers) + box.get_center(), 
                color=BLUE, 
                buff=0
        ).add_updater(
            lambda m: self.update_vector(
                mobj_vector=m, 
                mobj_tracker=f1_trackers, 
                center_mobj=box,
                color=BLUE
            )
        )
        vec1_name = Tex('$\\vec{F_1}$', color=BLUE)\
        .next_to(vec1, UP)
        
        vec2 = Arrow(
                start=box.get_center(), 
                end=self.ttnparr(f2_trackers) + box.get_center(), 
                color=RED, 
                buff=0
        ).add_updater(
            lambda m: self.update_vector(
                mobj_vector=m, 
                mobj_tracker=f2_trackers, 
                center_mobj=box,
                color=RED
            )
        )
        vec2_name = Tex('$\\vec{F_2}$', color=RED).next_to(vec2, UP)

        vec_sum = Arrow(
            start=box.get_center(),
            end=self.ttnparr(fsum_trackers) + box.get_center(),
            color=GREEN,
            buff=0,
            stroke_width=5
        ).add_updater(
            lambda m: self.update_vector(
                mobj_vector=m,
                mobj_tracker=fsum_trackers,
                center_mobj=box,
                color=GREEN,
                stroke_width=5
            )
        )
        vec_sum_name = Tex('$\\vec{F_1}+$'+'$\\vec{F_2}$', color=WHITE)\
        .next_to(vec_sum, UP)
        
        init_vectors = VGroup(vec1.copy(), vec2.copy())
        init_names = VGroup(
            vec1_name.copy().add_updater(lambda m: self.above_vector(m, init_vectors[0])),
            vec2_name.copy().add_updater(lambda m: self.above_vector(m, init_vectors[1]))
        )
        init_items = init_vectors + init_names
        sum_group = VGroup(
            vec_sum, 
            vec_sum_name.add_updater(lambda m: self.above_vector(m, vec_sum))
        )
        self.ttnparr(fsum_trackers)
        self.add(box, init_items)
        self.play(
            FadeOut(init_items),
            ReplacementTransform(
                init_items.copy(), 
                sum_group
            )
        )
        self.play(
            box.animate().shift(2*RIGHT)
        )
        self.play(
            FadeOut(sum_group),
            FadeIn(init_items),
        )
        self.play(
            f1_trackers[0].animate().set_value(-5),
            f2_trackers[0].animate().set_value(3),
            fsum_trackers[0].animate(),
            fsum_trackers[1].animate(),
            fsum_trackers[2].animate()
        )
        self.play(
            FadeOut(init_items),
            ReplacementTransform(init_items.copy(), sum_group)
        )
        self.play(
            box.animate().shift(2*LEFT)
        )
        self.play(
            FadeOut(sum_group),
            FadeIn(init_items),
        )
        self.play(
            f1_trackers[0].animate().set_value(0),
            f1_trackers[1].animate().set_value(-3)
        )
        self.play(
            FadeOut(init_items),
            ReplacementTransform(init_items.copy(), sum_group)
        )
        self.play(
            box.animate().shift(RIGHT+DOWN)
        )
        self.play(
            FadeOut(sum_group),
            FadeIn(init_items),
        )
        self.play(
            f2_trackers[0].animate().set_value(-3),
            f1_trackers[1].animate().set_value(+3)
        )
        self.play(
            FadeOut(init_items),
            ReplacementTransform(init_items.copy(), sum_group)
        )
        self.play(
            box.animate().shift(UP+LEFT)
        )
        self.play(
            FadeOut(sum_group),
            FadeIn(init_items),
        )
        self.play(
            f1_trackers[0].animate().set_value(-3),
            f2_trackers[0].animate().set_value(5),
            f1_trackers[1].animate().set_value(0)
        )

        print(self.ttnparr(f1_trackers))
        print(self.ttnparr(f2_trackers))
        print(self.ttnparr(fsum_trackers))

[-3.  0.  0.]
[5. 0. 0.]
[2. 0. 0.]


In [3]:
%%manim -qh -v WARNING --disable_caching Centripidal_acceleration

def statusis(vec):
    x = vec[0]
    y = vec[1]
    return np.array([-1*y, x, 0])

class Centripidal_acceleration(Scene):
    def construct(self):
        fps = 60
        dt = 1/60
        r = 3
        
        num_plane = NumberPlane()
        
        pth = Circle(color=BLUE, radius=r)
        red_dot = Dot([3, 0, 0], color=RED)
        a_vec = Arrow(
            start=np.array(red_dot.get_center()), 
            end=np.array([0,0,0]),
            buff=0, 
            color=RED
        ).add_updater(
            lambda m: m.become(Arrow(
                start=np.array(red_dot.get_center()), 
                buff=0, 
                end=np.array([0,0,0]), 
                color=RED)
            )
        )
        a_txt = Tex("pagreitis $\\vec{a}$", color=RED).next_to(a_vec)
        a_txt.add_updater(lambda m: m.next_to(a_vec))
        v_vec = Arrow(
            start=np.array(red_dot.get_center()), 
            end=red_dot.get_center() + statusis(red_dot.get_center()),
            buff=0,
            color=GREEN
        ).add_updater(
            lambda m: m.become(
                Arrow(
                    start=np.array(red_dot.get_center()), 
                    end=red_dot.get_center() + statusis(red_dot.get_center()),
                    buff=0,
                    color=GREEN
                )
            )
        )
        v_txt = Tex('greitis $\\vec{v}$', color = GREEN).add_updater(lambda m: m.move_to(v_vec))
        self.add(    
            num_plane,
            pth,
            red_dot,
            a_vec,
            v_vec,
            a_txt,
            v_txt
        )
        self.play(MoveAlongPath(red_dot, pth, run_time=5, rate_func=linear))
        

In [30]:
%%manim -ql -v WARNING --disable_caching Pendulum
import numpy.linalg as la

class Pendulum(Scene):
    def pendulum_movement(
        self, 
        pendulum_obj, 
        dt, 
        pin_obj,
        weight_force=np.array([0., -1., 0.])
    ):
        unit_towards = self.vec_end(
            pendulum_obj.get_center(),
            pin_obj,
            1
        )
        tension_force = self.vec_towards(
            pendulum_obj.get_center(), 
            pin_obj, 
            1.5*self.find_cos(
                unit_towards, 
                weight_force
            )*la.norm(weight_force)
        )
        sum_force = self.add_forces(weight_force, tension_force)
        acceleration = self.calculate_acceleration(sum_force)
        pendulum_obj.shift(self.velocity)
        self.calculate_velocity(a=acceleration, dt=dt)
        
    def calculate_velocity(self, a, dt):
        self.velocity = self.velocity + a * dt
        
    def calculate_acceleration(self, force, mass=1):
        return force/mass
        
    def add_forces(self, force1, force2):
        return force1 + force2
        
    def unit_vector(self, vector):
        return vector/la.norm(vector)
    
    def vec_towards(self, obj_coords, coords_towards, length):
        vec = coords_towards - obj_coords
        return self.unit_vector(vec) * length
    
    def vec_end(self, obj_coords, coords_towards, length):
        return self.vec_towards(obj_coords, coords_towards, length) + obj_coords

    def find_cos(self, vector1, vector2):
        unit_v_1 = self.unit_vector(vector1)
        unit_v_2 = self.unit_vector(vector2)
        print(np.dot(unit_v_1, unit_v_2))
        return np.dot(unit_v_1, unit_v_2) * (-1)
    def construct(self):
        fps = 60
        dt = 1/fps
        self.velocity = np.array([0.5, 0., 0.])
        
        pin = Dot(color=RED).shift(4*UP)
        ball = Circle(color=BLUE, fill_opacity=1, radius=1)
        ball.add_updater(
            lambda m, dt: self.pendulum_movement(
                m,
                dt,
                pin.get_center(),
            )
        )
        #Vectors and string (should be fine)
        string = Line(stroke_width=1, start=ball.get_center(), end=pin.get_center()).\
            add_updater(lambda m: m.become(Line(
                stroke_width=1, start=ball.get_center(), end=pin.get_center())
            ))
        tension_vector = Arrow(
            ball.get_center(), 
            self.vec_end(
                ball.get_center(), 
                pin.get_center(), 
                2
            ),
            buff=0,
            color=PURPLE
        ).add_updater(lambda m: m.become(Arrow(
            ball.get_center(), 
            self.vec_end(
                ball.get_center(), 
                pin.get_center(), 
                2
            ),
            buff=0,
            color=PURPLE))
        )
        weight_vector = Arrow(
            start=ball.get_center(),
            end=ball.get_center()+2*DOWN,
            color=PURPLE,
            buff=0
        ).add_updater(lambda m: m.put_start_and_end_on(
            ball.get_center(),
            ball.get_center() + 2 * DOWN
            )
        )
        self.add(ball, pin, string, tension_vector, weight_vector)
        self.wait(10)
        

-1.0


Waiting 0:   0%|          | 0/150 [00:00<?, ?it/s]

-0.9351274638573366


Waiting 0:  14%|#4        | 21/150 [00:00<00:02, 58.53it/s]

-0.7882054380161092
-0.6317571033536967
-0.5077861351663757
-0.4112126177968525
-0.33151880693784064
-0.26102625127014883
-0.19477225641915027
-0.12960889179174842
-0.0636283636591949
0.004135843525584643
0.07386609568677516
0.14507368827628853
0.2167323962703261
0.2874641597899622
0.3557705017564588
0.42026925239721324
0.4798828026335438
0.5339389575981698
0.5821779154288096
0.6246885636420605


Waiting 0:  21%|##        | 31/150 [00:00<00:01, 71.33it/s]

0.6618101791244139
0.6940315505191487
0.7219070108766046
0.745996395333841
0.7668277066666976
0.7848775662360308
0.8005638897049059
0.8142460781107997
0.8262292933889549
0.8367705651077441
0.8460853732952678
0.8543539658078781
0.861727055924857
0.8683307739430751
0.8742708712349534
0.879636236659298
0.8845018099875442
0.8889309817898104
0.8929775639801736
0.896687405652713
0.900099718055034


Waiting 0:  35%|###4      | 52/150 [00:00<00:01, 86.23it/s]

0.9032481621214151
0.9061617426328614
0.9088655450233007
0.9113813441049087
0.913728108423806
0.9159224194214125
0.9179788209028883
0.9199101113511612
0.9217275892410539
0.9234412595917812
0.9250600084557163
0.9265917508021512
0.9280435562565222
0.9294217563499596
0.9307320362825047
0.9319795136752062
0.9331688063570905
0.9343040908832809
0.9353891531947619
0.9364274325961627


Waiting 0:  48%|####8     | 72/150 [00:00<00:00, 92.03it/s]

0.9374220600355246
0.9383758915114894
0.9392915373023252
0.9401713876026365
0.94101763506337
0.9418322946555304
0.9426172212151789
0.9433741249746369
0.9441045853405657
0.94481006314234
0.9454919115426482
0.9461513857756156
0.9467896518551185
0.9474077943767274
0.9480068235202902
0.9485876813461559
0.9491512474660023
0.949698344158925
0.9502297409945558
0.9507461590173217


Waiting 0:  61%|######1   | 92/150 [00:01<00:00, 94.55it/s]

0.9512482745393408
0.9517367225837143
0.95221210001501
0.9526749683893984
0.9531258565531538
0.9535652630149319
0.9539936581143724
0.954411486007062
0.9548191664836786
0.9552170966392093
0.9556056524064181
0.9559851899662467
0.9563560470464886
0.9567185441189194
0.9570729855040089
0.957419660391429
0.9577588437837475
0.9580907973699666
0.9584157703349189
0.9587340001099497


Waiting 0:  75%|#######4  | 112/150 [00:01<00:00, 95.33it/s]

0.9590457130698024
0.9593511251801515
0.9596504425998242
0.9599438622413701
0.9602315722933065
0.9605137527070745
0.9607905756514569
0.9610622059369782
0.9613288014125796
0.961590513336667
0.9618474867244499
0.9620998606733264
0.9623477686679225
0.9625913388662605
0.962830694368412
0.9630659534688795
0.9632972298938464
0.9635246330243552
0.9637482681063777
0.9639682364486747


Waiting 0:  88%|########8 | 132/150 [00:01<00:00, 96.09it/s]

0.9641846356092685
0.9643975595712903
0.9646070989089075
0.964813340943979
0.9650163698940449
0.9652162670122055
0.9654131107194074
0.9656069767296181
0.9657979381683334
0.9659860656848288
0.9661714275585461
0.9663540897999625
0.9665341162462866
0.9667115686522814
0.9668865067765097
0.9670589884632672
0.9672290697204572
0.967396804793641
0.9675622462364808
0.967725444977784


0.9678864503853378
0.9680453103267135
0.9682020712272101
0.9683567781250928
0.968509474724274
0.9686602034445766
0.9688090054697082
0.968955920793067
0.9691009882614963
